import Banner from '../../Components/Banner';
import Header from '../../Components/Header';
import './globals.css';

export const metadata = {
  title: 'Jaguar blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='max-w-7xl mx-auto'>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );
}
